
@baseUrl = http://localhost:3000/auth
 ####
POST {{baseUrl}}/login
 Content-Type: application/json 

 {
    "username":"admin",
    "password":"admin"
 }  

###
DELETE http://localhost:3000/message/30

###
PATCH  http://localhost:3000/message/31
 Content-Type: application/json 

{
   "type":"question",
   "content":"changement"
}
###
POST {{baseUrl}}/register
 Content-Type: application/json 

 {
    "username":"admin",
    "password":"admi"
 }  

###
POST {{baseUrl}}/login
 Content-Type: application/json 

 {
    "username":"user",
    "password":"zayz"
 }  
###
POST {{baseUrl}}/login
 Content-Type: application/json 

 {
    "username":"uss",
    "password":"11"
 }  

###
POST  http://localhost:3000/message/addMessageUser
  Content-Type: application/json 

 {
    "content":"uss",
    "type":"question"
 } 

###
GET {{baseUrl}}/logout

###


###
POST {{baseUrl}}/loginAnonyme
 Content-Type: application/json 

 {
    "username":"user3"
 }  
 
###
GET http://localhost:3000/point

###
POST http://localhost:3000/point
Content-Type: application/json

{
   "nbePoint":"3",
   "nbeErreu":"5"
}

### 
POST http://localhost:3000/message/addMessageUser
Content-Type: application/json

{
   "content":"message3",
   "type":"suggestion"
}

### 
POST http://localhost:3000/message/addMessageVisitor
Content-Type: application/json

{
   "content":"message1",
   "type":"question"
}